siteTitle="AID Berkeley"

linkPrefix = "/"

[contact]
"AID Global" = "https://aidindia.org"
"AID Bay Area" = "https://aidbayarea.org"
"Email" = "info@bayarea.aidinida.org"

[social]
facebook = "https://www.facebook.com/aidberkeley"
